"""NEURON V4 — incremental upgrades over V3.9.

This package does NOT replace AgentLoop. It adds typed state objects and
DesktopWorldModel that wraps existing `neuron.brain` / `neuron.v3` state.

See: backend/docs/V4_ARCHITECTURE_AUDIT.md
     backend/docs/V4_1_DESKTOP_WORLD_MODEL.md
"""

from __future__ import annotations

from neuron.v4.types import (
    Action,
    ActionResult,
    AgentState,
    Goal,
    Observation,
    Plan,
    PlanStep,
    RecoveryDecision,
    Task,
    VerificationOutcome,
    VerificationResult,
)
from neuron.v4.world import (
    ApplicationState,
    BrowserState,
    DesktopState,
    DesktopWorldModel,
    InteractionRecord,
    KnowledgeLevel,
    MonitorState,
    UIElementState,
    WindowState,
    get_world_model,
    reset_world_model,
)
from neuron.v4.perception import (
    PerceptionEngine,
    PerceptionResult,
    get_perception_engine,
    reset_perception_engine,
)
from neuron.v4.resolve import (
    ResolutionResult,
    ResolutionStatus,
    SemanticElementResolver,
    get_semantic_resolver,
    reset_semantic_resolver,
    resolve as resolve_element_v4,
)
from neuron.v4.plan import (
    ActionIntent,
    DecisionKind,
    GroundedAction,
    HierarchicalPlanner,
    PlanStatus,
    PlanningDecision,
    StepStatus,
    Subgoal,
    TaskPlan,
    get_hierarchical_planner,
    reset_hierarchical_planner,
)
from neuron.v4.plan.types import Goal as PlanGoal
from neuron.v4.verify import (
    ExpectationKind,
    VerificationEngine,
    VerificationExpectation,
    VerificationReport,
    get_verification_engine,
    reset_verification_engine,
)
from neuron.v4.recover import (
    FailureCategory,
    RecoveryEngine,
    RecoveryKind,
    RecoveryDecision as V4RecoveryDecision,
    get_recovery_engine,
    reset_recovery_engine,
)
from neuron.v4.context import (
    ConversationEngine,
    ConversationState,
    ContinuityKind,
    IntentFamily,
    RouteDest,
    get_conversation_engine,
    reset_conversation_engine,
    understand_for_agent,
)
from neuron.v4.capability import (
    CapabilityCatalog,
    CapabilityDescriptor,
    CapabilityDomain,
    CapabilityResolution,
    get_capability_catalog,
    reset_capability_catalog,
    resolve_intent,
    coverage_report,
)
from neuron.v4.learn import (
    ProcedureDefinition,
    VerifiedTaskTrace,
    get_procedure_registry,
    reset_procedure_registry,
    procedure_learning_enabled,
    learn_metrics,
)
from neuron.v4.voice import (
    hierarchical_voice_enabled,
    voice_routing_mode,
    VoiceRoutingMode,
    reset_voice_metrics,
    voice_metrics,
)

__all__ = [
    "Goal",
    "Task",
    "Plan",
    "PlanStep",
    "Observation",
    "Action",
    "ActionResult",
    "VerificationOutcome",
    "VerificationResult",
    "RecoveryDecision",
    "AgentState",
    "DesktopWorldModel",
    "DesktopState",
    "MonitorState",
    "WindowState",
    "ApplicationState",
    "BrowserState",
    "UIElementState",
    "InteractionRecord",
    "KnowledgeLevel",
    "get_world_model",
    "reset_world_model",
    "PerceptionEngine",
    "PerceptionResult",
    "get_perception_engine",
    "reset_perception_engine",
    "SemanticElementResolver",
    "ResolutionResult",
    "ResolutionStatus",
    "get_semantic_resolver",
    "reset_semantic_resolver",
    "resolve_element_v4",
    "HierarchicalPlanner",
    "PlanGoal",
    "TaskPlan",
    "Subgoal",
    "ActionIntent",
    "GroundedAction",
    "PlanningDecision",
    "PlanStatus",
    "StepStatus",
    "DecisionKind",
    "get_hierarchical_planner",
    "reset_hierarchical_planner",
    "VerificationEngine",
    "VerificationReport",
    "VerificationExpectation",
    "ExpectationKind",
    "get_verification_engine",
    "reset_verification_engine",
    "RecoveryEngine",
    "FailureCategory",
    "RecoveryKind",
    "V4RecoveryDecision",
    "get_recovery_engine",
    "reset_recovery_engine",
    "ConversationEngine",
    "ConversationState",
    "ContinuityKind",
    "IntentFamily",
    "RouteDest",
    "get_conversation_engine",
    "reset_conversation_engine",
    "understand_for_agent",
    "CapabilityCatalog",
    "CapabilityDescriptor",
    "CapabilityDomain",
    "CapabilityResolution",
    "get_capability_catalog",
    "reset_capability_catalog",
    "resolve_intent",
    "coverage_report",
    "ProcedureDefinition",
    "VerifiedTaskTrace",
    "get_procedure_registry",
    "reset_procedure_registry",
    "procedure_learning_enabled",
    "learn_metrics",
    "hierarchical_voice_enabled",
    "voice_routing_mode",
    "VoiceRoutingMode",
    "reset_voice_metrics",
    "voice_metrics",
]
