"""Generate Unreal Editor Python, C++ stubs, and guidance artifacts."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from neuron.unreal_agent.runner import assets_root, write_text


def _py_header() -> str:
    return '''"""Generated by NEURON Unreal Agent — Unreal Editor Python."""
import unreal

def log(msg: str) -> None:
    unreal.log(f"[NEURON] {msg}")

'''


def script_third_person_character(name: str = "TP_Character") -> tuple[str, str]:
    """Editor Python that scaffolds a Character Blueprint + notes for GameMode."""
    src = _py_header() + f'''
char_path = "/Game/NEURON/{name}"
factory = unreal.BlueprintFactory()
factory.set_editor_property("ParentClass", unreal.Character)
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
try:
    bp = asset_tools.create_asset("{name}", "/Game/NEURON", unreal.Blueprint, factory)
    log(f"Created Character Blueprint: {{bp.get_path_name() if bp else char_path}}")
except Exception as exc:
    log(f"Blueprint create note: {{exc}} — ensure /Game/NEURON exists or create folder in Content Browser.")

# Add a simple camera boom / follow camera components via default subobject guidance
log("Next: open {name}, add SpringArm + Camera, set Auto Possess Player to Player 0.")
log("NEURON_UNREAL_OK third_person_character")
'''
    path = write_text(f"scripts/tp_character_{name}.py", src)
    # Also emit C++ stub
    h = f'''#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Character.h"
#include "Camera/CameraComponent.h"
#include "GameFramework/SpringArmComponent.h"
#include "{name}.generated.h"

UCLASS()
class A{name} : public ACharacter
{{
	GENERATED_BODY()
public:
	A{name}();
protected:
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Camera")
	USpringArmComponent* CameraBoom;
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category="Camera")
	UCameraComponent* FollowCamera;
	virtual void SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent) override;
}};
'''
    cpp = f'''#include "{name}.h"
#include "GameFramework/Controller.h"
#include "EnhancedInputComponent.h"

A{name}::{name}()
{{
	PrimaryActorTick.bCanEverTick = false;
	CameraBoom = CreateDefaultSubobject<USpringArmComponent>(TEXT("CameraBoom"));
	CameraBoom->SetupAttachment(RootComponent);
	CameraBoom->TargetArmLength = 400.f;
	CameraBoom->bUsePawnControlRotation = true;
	FollowCamera = CreateDefaultSubobject<UCameraComponent>(TEXT("FollowCamera"));
	FollowCamera->SetupAttachment(CameraBoom, USpringArmComponent::SocketName);
	FollowCamera->bUsePawnControlRotation = false;
}}

void A{name}::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{{
	Super::SetupPlayerInputComponent(PlayerInputComponent);
	// Bind Move/Look via Enhanced Input in the editor or project defaults.
}}
'''
    write_text(f"cpp/{name}.h", h)
    write_text(f"cpp/{name}.cpp", cpp)
    return str(path), src


def script_niagara_fire(name: str = "NS_Fire") -> tuple[str, str]:
    src = _py_header() + f'''
# Niagara system scaffold (requires Niagara plugin enabled)
try:
    factory = unreal.NiagaraSystemFactoryNew()
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    sys = asset_tools.create_asset("{name}", "/Game/NEURON/FX", unreal.NiagaraSystem, factory)
    log(f"Created Niagara system: {{sys.get_path_name() if sys else '{name}'}}")
except Exception as exc:
    log(f"Niagara create: {{exc}}")
log("Recommended emitters: Spawn Rate flame + smoke; Sprite Renderer; Color over life orange->black; Size by velocity.")
log("NEURON_UNREAL_OK niagara_fire")
'''
    path = write_text(f"scripts/niagara_fire_{name}.py", src)
    guide = write_text(
        f"assets/{name}_guide.md",
        f"""# {name} — Niagara Fire

1. Enable **Niagara** plugin.
2. Create System `{name}` under `/Game/NEURON/FX` (script attempts this).
3. Emitter A (Flame): Spawn Rate 40-80, Sprite, Additive, Color orange→yellow→transparent.
4. Emitter B (Smoke): Spawn Rate 10-20, larger soft sprites, slow rise, gray alpha fade.
5. Optional: Curl Noise force for turbulence; Point Attraction toward torch tip.
6. Place `Niagara Actor` in level and scale.
""",
    )
    return str(path), src


def script_material(name: str = "M_Neuron") -> tuple[str, str]:
    src = _py_header() + f'''
try:
    factory = unreal.MaterialFactoryNew()
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    mat = asset_tools.create_asset("{name}", "/Game/NEURON/Materials", unreal.Material, factory)
    log(f"Created material: {{mat.get_path_name() if mat else '{name}'}}")
except Exception as exc:
    log(f"Material create: {{exc}}")
log("Open material: add Constant3Vector base color, multiply with TextureSample, plug into Base Color; set Roughness 0.4.")
log("NEURON_UNREAL_OK material")
'''
    return str(write_text(f"scripts/material_{name}.py", src)), src


def script_landscape() -> tuple[str, str]:
    src = _py_header() + '''
log("Landscape: use Modes > Landscape > Manage > Create New. Quads 63, Sections 1x1, Overall Resolution ~1009 for mid-size.")
log("Sculpt: noise + smooth; paint layers Grass/Dirt/Rock with Landscape Layer Info.")
log("NEURON_UNREAL_OK landscape")
'''
    path = write_text("scripts/landscape_guide.py", src)
    write_text(
        "assets/landscape_checklist.md",
        """# Landscape checklist\n\n- Create landscape actor\n- Enable Edit Layers\n- Add material with Layer Blend\n- Paint weightmaps\n- Add foliage types\n- Build lighting / virtual textures as needed\n""",
    )
    return str(path), src


def script_lighting() -> tuple[str, str]:
    src = _py_header() + '''
# Place a Directional Light + Sky Atmosphere if missing
editor_level_lib = unreal.EditorLevelLibrary
actors = editor_level_lib.get_all_level_actors()
has_dir = any(isinstance(a, unreal.DirectionalLight) for a in actors)
if not has_dir:
    light = editor_level_lib.spawn_actor_from_class(unreal.DirectionalLight, unreal.Vector(0, 0, 500))
    log(f"Spawned DirectionalLight: {light}")
log("Enable Lumen (or bake Lightmass for static). Add SkyAtmosphere + ExponentialHeightFog + SkyLight.")
log("NEURON_UNREAL_OK lighting")
'''
    return str(write_text("scripts/lighting_setup.py", src)), src


def script_sequencer(name: str = "LS_NeuronShot") -> tuple[str, str]:
    src = _py_header() + f'''
try:
    factory = unreal.LevelSequenceFactoryNew()
    asset_tools = unreal.AssetToolsHelpers.get_asset_tools()
    seq = asset_tools.create_asset("{name}", "/Game/NEURON/Cinematics", unreal.LevelSequence, factory)
    log(f"Created Level Sequence: {{seq.get_path_name() if seq else '{name}'}}")
except Exception as exc:
    log(f"Sequencer: {{exc}}")
log("Open Sequencer: add Camera Cut track + Transform tracks; set frame rate 30; render via Movie Render Queue.")
log("NEURON_UNREAL_OK sequencer")
'''
    return str(write_text(f"scripts/sequencer_{name}.py", src)), src


def script_animation_notes() -> tuple[str, str]:
    src = _py_header() + '''
log("Animation: import FBX skeleton; create Animation Blueprint with State Machine (Idle/Walk/Run/Jump).")
log("Use Control Rig or IK Retargeter for mannequin retargeting.")
log("NEURON_UNREAL_OK animation")
'''
    return str(write_text("scripts/animation_guide.py", src)), src


def cpp_actor_stub(name: str = "NeuronActor") -> Path:
    h = f'''#pragma once
#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "{name}.generated.h"

UCLASS()
class A{name} : public AActor
{{
	GENERATED_BODY()
public:
	A{name}();
protected:
	virtual void BeginPlay() override;
public:
	virtual void Tick(float DeltaTime) override;
}};
'''
    cpp = f'''#include "{name}.h"

A{name}::{name}()
{{
	PrimaryActorTick.bCanEverTick = true;
}}

void A{name}::BeginPlay()
{{
	Super::BeginPlay();
}}

void A{name}::Tick(float DeltaTime)
{{
	Super::Tick(DeltaTime);
}}
'''
    write_text(f"cpp/{name}.h", h)
    return write_text(f"cpp/{name}.cpp", cpp)


def blueprint_guide(kind: str = "generic") -> Path:
    return write_text(
        f"blueprints/{kind}_guide.md",
        f"""# Blueprint guide — {kind}

## Graph hygiene
- Prefer functions over Copy-Paste event spaghetti
- Collapse macros sparingly; prefer functions for typed IO
- Use Gameplay Tags / Interfaces for coupling

## Common nodes
- Event BeginPlay / Tick (avoid heavy Tick)
- Cast / IsValid checks
- Timeline for simple interpolations
""",
    )


def optimization_plan() -> dict[str, Any]:
    tips = [
        "Profile with `stat unit` / `stat fps` / Unreal Insights before changing art.",
        "Reduce dynamic lights; prefer Lumen settings tuned for target platform.",
        "Enable Nanite for dense static meshes; watch material overdraw.",
        "Cull with HLOD / World Partition streaming for large worlds.",
        "Lower Shadow Cascade count; use Virtual Shadow Maps carefully.",
        "Compress textures (DXT/BC); avoid 4K where 1K/2K suffices.",
        "Replace Tick logic with Timers / Event-driven updates.",
        "Niagara: budget particle counts; GPU sim when appropriate.",
        "r.ScreenPercentage / TSR for upscaling on mid GPUs.",
        "Cook with -iterate and check Shader Compile Worker bottlenecks.",
    ]
    path = write_text(
        "assets/optimization_fps.md",
        "# FPS Optimization\n\n" + "\n".join(f"- {t}" for t in tips),
    )
    return {"tips": tips, "path": str(path)}


def packaging_plan(project: str | None = None, config: str = "Shipping") -> dict[str, Any]:
    proj = project or "YourGame.uproject"
    args = [
        "BuildCookRun",
        f"-project={proj}",
        "-noP4",
        "-platform=Win64",
        f"-clientconfig={config}",
        "-cook",
        "-build",
        "-stage",
        "-pak",
        "-archive",
    ]
    path = write_text(
        "builds/package_command.txt",
        "RunUAT " + " ".join(args) + "\n",
    )
    return {"uat_args": args, "path": str(path), "notes": [
        "File > Package Project also works from the Editor.",
        "Fix packaging errors from Output Log / UAT log first.",
        "Include Prerequisites and set Maps to cook.",
    ]}


def build_monitor_plan(project: str | None = None) -> dict[str, Any]:
    return {
        "commands": [
            "Build from IDE (Development Editor)",
            "UnrealBuildTool Win64 Development",
            "Live Coding Ctrl+Alt+F11",
        ],
        "watch": [
            "ShaderCompileWorker",
            "UBT log in Saved/Logs",
            "Error/Warning counts",
        ],
        "project": project,
    }


def parse_crash(text: str) -> dict[str, Any]:
    raw = text or ""
    findings: list[dict[str, Any]] = []
    import re
    for m in re.finditer(r"(Fatal error|Assertion failed|Unhandled Exception)[:\s]+(.+)", raw, re.I):
        findings.append({"kind": "fatal", "message": m.group(0)[:300]})
    for m in re.finditer(r"(UE4Editor|UnrealEditor)[^\n]+", raw):
        findings.append({"kind": "module", "message": m.group(0)[:200]})
    for m in re.finditer(r"([A-Za-z0-9_]+::[A-Za-z0-9_]+)\(\)", raw):
        findings.append({"kind": "symbol", "message": m.group(1)})
    for m in re.finditer(r"Log[A-Za-z]+:\s*Error:\s*(.+)", raw):
        findings.append({"kind": "log_error", "message": m.group(1)[:240]})
    primary = findings[0]["message"] if findings else "No clear crash signature — paste Saved/Logs crash context."
    advice = [
        "Open the matching .pdb symbols if a callstack is truncated.",
        "Reproduce with `-log` and check `Saved/Logs/*.log`.",
        "Check recent C++ changes around asserted pointers (IsValid).",
        "Disable suspect plugins; binary-search maps.",
    ]
    path = write_text("logs/last_crash_analysis.md", f"# Crash analysis\n\nPrimary: {primary}\n\n" + "\n".join(f"- {a}" for a in advice))
    return {"findings": findings[:30], "primary": primary, "advice": advice, "path": str(path)}
