"""Generate Blender Python (bpy) scripts for expert workflows."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from neuron.blender_agent.runner import assets_root


def _header() -> str:
    return '''"""Generated by NEURON Blender Agent — bpy script."""
import bpy
from mathutils import Vector, Euler
import math

def _clear_mesh_objects():
    bpy.ops.object.select_all(action='DESELECT')
    for obj in list(bpy.data.objects):
        if obj.type == 'MESH':
            obj.select_set(True)
    bpy.ops.object.delete()

def _ensure_object_mode():
    if bpy.context.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')

'''


def script_soda_can(*, name: str = "SodaCan") -> str:
    out = (assets_root() / "exports" / f"{name}.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
# Realistic soda can: body cylinder + top/bottom + metallic material
bpy.ops.mesh.primitive_cylinder_add(vertices=64, radius=0.033, depth=0.122, location=(0, 0, 0.061))
body = bpy.context.active_object
body.name = "{name}_Body"

# Top lid (slightly inset)
bpy.ops.mesh.primitive_cylinder_add(vertices=64, radius=0.032, depth=0.004, location=(0, 0, 0.124))
top = bpy.context.active_object
top.name = "{name}_Top"

# Bottom
bpy.ops.mesh.primitive_cylinder_add(vertices=64, radius=0.032, depth=0.004, location=(0, 0, 0.002))
bottom = bpy.context.active_object
bottom.name = "{name}_Bottom"

# Tab (simple cube scaled)
bpy.ops.mesh.primitive_cube_add(size=0.01, location=(0.0, 0.012, 0.127))
tab = bpy.context.active_object
tab.name = "{name}_Tab"
tab.scale = (1.6, 0.6, 0.15)

def metal_mat(mat_name, base=(0.75, 0.75, 0.78, 1.0), rough=0.25, metal=1.0):
    mat = bpy.data.materials.new(name=mat_name)
    mat.use_nodes = True
    nt = mat.node_tree
    bsdf = nt.nodes.get("Principled BSDF")
    if bsdf:
        bsdf.inputs["Base Color"].default_value = base
        bsdf.inputs["Metallic"].default_value = metal
        bsdf.inputs["Roughness"].default_value = rough
    return mat

body_mat = metal_mat("{name}_Metal", (0.8, 0.12, 0.12, 1.0), rough=0.22)
top_mat = metal_mat("{name}_Aluminum", (0.7, 0.7, 0.72, 1.0), rough=0.18)
for obj, mat in ((body, body_mat), (top, top_mat), (bottom, top_mat), (tab, top_mat)):
    if obj.data.materials:
        obj.data.materials[0] = mat
    else:
        obj.data.materials.append(mat)

# Join
for obj in (top, bottom, tab):
    obj.select_set(True)
body.select_set(True)
bpy.context.view_layer.objects.active = body
bpy.ops.object.join()
body.name = "{name}"

# Camera + light
if "Camera" not in bpy.data.objects:
    bpy.ops.object.camera_add(location=(0.25, -0.35, 0.18))
cam = bpy.data.objects["Camera"]
cam.location = (0.25, -0.35, 0.18)
cam.rotation_euler = Euler((math.radians(72), 0, math.radians(35)), 'XYZ')
bpy.context.scene.camera = cam

if "Light" not in bpy.data.objects:
    bpy.ops.object.light_add(type='AREA', location=(0.4, -0.2, 0.5))
light = bpy.data.objects.get("Light") or bpy.context.active_object
light.data.energy = 250
light.data.size = 0.4

bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK soda_can -> {out}")
'''


def script_create_object(kind: str = "cube", name: str = "NeuronObject") -> str:
    kind = (kind or "cube").lower()
    ops = {
        "cube": "bpy.ops.mesh.primitive_cube_add(size=2, location=(0,0,1))",
        "sphere": "bpy.ops.mesh.primitive_uv_sphere_add(radius=1, location=(0,0,1))",
        "cylinder": "bpy.ops.mesh.primitive_cylinder_add(radius=1, depth=2, location=(0,0,1))",
        "plane": "bpy.ops.mesh.primitive_plane_add(size=4, location=(0,0,0))",
        "torus": "bpy.ops.mesh.primitive_torus_add(location=(0,0,1))",
        "cone": "bpy.ops.mesh.primitive_cone_add(radius1=1, depth=2, location=(0,0,1))",
        "monkey": "bpy.ops.mesh.primitive_monkey_add(location=(0,0,1))",
    }
    op = ops.get(kind, ops["cube"])
    out = (assets_root() / "exports" / f"{name}.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
{op}
obj = bpy.context.active_object
obj.name = "{name}"
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK create_{kind} -> {out}")
'''


def script_material(name: str = "NeuronMaterial", style: str = "procedural") -> str:
    out = (assets_root() / "exports" / f"{name}.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
# Target active mesh or create a sphere
if not bpy.context.active_object or bpy.context.active_object.type != 'MESH':
    bpy.ops.mesh.primitive_uv_sphere_add(radius=1, location=(0,0,1))
obj = bpy.context.active_object
mat = bpy.data.materials.new(name="{name}")
mat.use_nodes = True
nt = mat.node_tree
nodes = nt.nodes
links = nt.links
nodes.clear()
out_n = nodes.new("ShaderNodeOutputMaterial")
bsdf = nodes.new("ShaderNodeBsdfPrincipled")
noise = nodes.new("ShaderNodeTexNoise")
colorramp = nodes.new("ShaderNodeValToRGB")
noise.inputs["Scale"].default_value = 6.0
noise.inputs["Detail"].default_value = 8.0
colorramp.color_ramp.elements[0].color = (0.05, 0.08, 0.2, 1)
colorramp.color_ramp.elements[1].color = (0.7, 0.75, 0.9, 1)
links.new(noise.outputs["Fac"], colorramp.inputs["Fac"])
links.new(colorramp.outputs["Color"], bsdf.inputs["Base Color"])
bsdf.inputs["Roughness"].default_value = 0.35
bsdf.inputs["Metallic"].default_value = 0.15
links.new(bsdf.outputs["BSDF"], out_n.inputs["Surface"])
if obj.data.materials:
    obj.data.materials[0] = mat
else:
    obj.data.materials.append(mat)
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK material_{style} -> {out}")
'''


def script_geometry_nodes(name: str = "NeuronGeoNodes") -> str:
    out = (assets_root() / "exports" / f"{name}.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
bpy.ops.mesh.primitive_plane_add(size=4, location=(0,0,0))
obj = bpy.context.active_object
obj.name = "{name}_Grid"

mod = obj.modifiers.new(name="{name}", type='NODES')
node_group = bpy.data.node_groups.new(name="{name}", type='GeometryNodeTree')
mod.node_group = node_group
nodes = node_group.nodes
links = node_group.links
nodes.clear()
# Blender 3+ geometry nodes interface
try:
    node_group.interface.new_socket(name="Geometry", in_out='INPUT', socket_type='NodeSocketGeometry')
    node_group.interface.new_socket(name="Geometry", in_out='OUTPUT', socket_type='NodeSocketGeometry')
except Exception:
    pass
nin = nodes.new("NodeGroupInput")
nout = nodes.new("NodeGroupOutput")
subdiv = nodes.new("GeometryNodeSubdivisionSurface")
displace = nodes.new("GeometryNodeSetPosition")
noise = nodes.new("ShaderNodeTexNoise")
nin.location = (-400, 0)
subdiv.location = (-150, 0)
noise.location = (-150, -200)
displace.location = (100, 0)
nout.location = (350, 0)
noise.inputs["Scale"].default_value = 4.0
links.new(nin.outputs[0], subdiv.inputs["Mesh"])
links.new(subdiv.outputs["Mesh"], displace.inputs["Geometry"])
# Offset via noise on Z — simplified: pass through if sockets mismatch
try:
    links.new(displace.outputs["Geometry"], nout.inputs[0])
except Exception:
    links.new(subdiv.outputs["Mesh"], nout.inputs[0])
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK geometry_nodes -> {out}")
'''


def script_lighting(style: str = "studio") -> str:
    out = (assets_root() / "exports" / "lighting_setup.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
# Remove existing lights
for obj in list(bpy.data.objects):
    if obj.type == 'LIGHT':
        bpy.data.objects.remove(obj, do_unlink=True)
# Three-point studio lighting
bpy.ops.object.light_add(type='AREA', location=(3, -2, 4))
key = bpy.context.active_object
key.name = "KeyLight"
key.data.energy = 400
key.data.size = 2.0
bpy.ops.object.light_add(type='AREA', location=(-3, -1, 3))
fill = bpy.context.active_object
fill.name = "FillLight"
fill.data.energy = 120
fill.data.size = 3.0
bpy.ops.object.light_add(type='AREA', location=(0, 3, 2))
rim = bpy.context.active_object
rim.name = "RimLight"
rim.data.energy = 200
rim.data.size = 1.5
world = bpy.context.scene.world
if world is None:
    world = bpy.data.worlds.new("World")
    bpy.context.scene.world = world
world.use_nodes = True
bg = world.node_tree.nodes.get("Background")
if bg:
    bg.inputs[0].default_value = (0.02, 0.02, 0.03, 1)
    bg.inputs[1].default_value = 0.3
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK lighting_{style} -> {out}")
'''


def script_camera(name: str = "NeuronCam") -> str:
    out = (assets_root() / "exports" / "camera_setup.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
bpy.ops.object.camera_add(location=(4, -4, 2.5))
cam = bpy.context.active_object
cam.name = "{name}"
cam.rotation_euler = Euler((math.radians(65), 0, math.radians(45)), 'XYZ')
cam.data.lens = 50
bpy.context.scene.camera = cam
# Track-to empty at origin
bpy.ops.object.empty_add(type='PLAIN_AXES', location=(0,0,1))
empty = bpy.context.active_object
empty.name = "{name}_Target"
con = cam.constraints.new(type='TRACK_TO')
con.target = empty
con.track_axis = 'TRACK_NEGATIVE_Z'
con.up_axis = 'UP_Y'
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK camera -> {out}")
'''


def script_render(engine: str = "CYCLES", samples: int = 64, filepath: str | None = None) -> str:
    engine = (engine or "CYCLES").upper()
    if engine not in ("CYCLES", "BLENDER_EEVEE", "BLENDER_EEVEE_NEXT", "EEVEE"):
        engine = "CYCLES"
    if engine == "EEVEE":
        engine = "BLENDER_EEVEE"
    fp = filepath or (assets_root() / "renders" / "neuron_render.png").as_posix()
    return _header() + f'''
scene = bpy.context.scene
scene.render.engine = "{engine}"
scene.render.filepath = r"{fp}"
scene.render.image_settings.file_format = "PNG"
scene.render.resolution_x = 1280
scene.render.resolution_y = 720
if scene.render.engine == "CYCLES":
    scene.cycles.samples = {int(samples)}
    try:
        scene.cycles.device = "GPU"
    except Exception:
        pass
# Ensure camera exists
if scene.camera is None:
    bpy.ops.object.camera_add(location=(4, -4, 3))
    cam = bpy.context.active_object
    cam.rotation_euler = Euler((math.radians(60), 0, math.radians(45)), 'XYZ')
    scene.camera = cam
bpy.ops.render.render(write_still=True)
print("NEURON_BLENDER_OK render_{engine} -> {fp}")
'''


def script_animation(frames: int = 60) -> str:
    out = (assets_root() / "exports" / "animation.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
if not bpy.context.active_object:
    bpy.ops.mesh.primitive_cube_add(location=(0,0,1))
obj = bpy.context.active_object
scene = bpy.context.scene
scene.frame_start = 1
scene.frame_end = {int(frames)}
obj.location = (0, 0, 1)
obj.keyframe_insert(data_path="location", frame=1)
obj.location = (2, 0, 1)
obj.keyframe_insert(data_path="location", frame={int(frames)//2})
obj.location = (0, 0, 1)
obj.keyframe_insert(data_path="location", frame={int(frames)})
obj.rotation_euler = (0, 0, 0)
obj.keyframe_insert(data_path="rotation_euler", frame=1)
obj.rotation_euler = (0, 0, math.radians(360))
obj.keyframe_insert(data_path="rotation_euler", frame={int(frames)})
# Ease
for fc in obj.animation_data.action.fcurves:
    for kp in fc.keyframe_points:
        kp.interpolation = 'BEZIER'
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK animation -> {out}")
'''


def script_rigging() -> str:
    out = (assets_root() / "exports" / "rig.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
# Simple armature + parent mesh
bpy.ops.mesh.primitive_cylinder_add(radius=0.2, depth=2, location=(0,0,1))
mesh = bpy.context.active_object
mesh.name = "Character_Mesh"
bpy.ops.object.armature_add(enter_editmode=True, location=(0,0,0))
arm = bpy.context.active_object
arm.name = "Character_Armature"
ebones = arm.data.edit_bones
root = ebones[0]
root.name = "Root"
root.head = (0, 0, 0)
root.tail = (0, 0, 0.5)
spine = ebones.new("Spine")
spine.head = root.tail
spine.tail = (0, 0, 1.2)
spine.parent = root
head = ebones.new("Head")
head.head = spine.tail
head.tail = (0, 0, 1.6)
head.parent = spine
bpy.ops.object.mode_set(mode='OBJECT')
mesh.select_set(True)
arm.select_set(True)
bpy.context.view_layer.objects.active = arm
bpy.ops.object.parent_set(type='ARMATURE_AUTO')
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK rigging -> {out}")
'''


def script_physics() -> str:
    out = (assets_root() / "exports" / "physics.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
bpy.ops.mesh.primitive_plane_add(size=6, location=(0,0,0))
ground = bpy.context.active_object
ground.name = "Ground"
bpy.ops.rigidbody.object_add()
ground.rigid_body.type = 'PASSIVE'
bpy.ops.mesh.primitive_uv_sphere_add(radius=0.4, location=(0, 0, 3))
ball = bpy.context.active_object
ball.name = "Ball"
bpy.ops.rigidbody.object_add()
ball.rigid_body.type = 'ACTIVE'
ball.rigid_body.mass = 1.0
bpy.context.scene.frame_end = 120
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK physics -> {out}")
'''


def script_topology_fix() -> str:
    out = (assets_root() / "exports" / "topology_fixed.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
obj = bpy.context.active_object
if obj is None or obj.type != 'MESH':
    bpy.ops.mesh.primitive_monkey_add(location=(0,0,1))
    obj = bpy.context.active_object
bpy.ops.object.mode_set(mode='EDIT')
bpy.ops.mesh.select_all(action='SELECT')
bpy.ops.mesh.remove_doubles(threshold=0.0001)
bpy.ops.mesh.normals_make_consistent(inside=False)
bpy.ops.mesh.dissolve_degenerate()
bpy.ops.object.mode_set(mode='OBJECT')
# Optional remesh for messy geo
try:
    remesh = obj.modifiers.new(name="NeuronRemesh", type='REMESH')
    remesh.mode = 'VOXEL'
    remesh.voxel_size = 0.05
    bpy.ops.object.modifier_apply(modifier=remesh.name)
except Exception as exc:
    print("remesh_skip", exc)
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK topology -> {out}")
'''


def script_import(path: str) -> str:
    p = Path(path).as_posix()
    out = (assets_root() / "exports" / "imported.blend").as_posix()
    return _header() + f'''
_ensure_object_mode()
fp = r"{p}"
low = fp.lower()
if low.endswith('.obj'):
    bpy.ops.wm.obj_import(filepath=fp) if hasattr(bpy.ops.wm, 'obj_import') else bpy.ops.import_scene.obj(filepath=fp)
elif low.endswith('.fbx'):
    bpy.ops.import_scene.fbx(filepath=fp)
elif low.endswith('.gltf') or low.endswith('.glb'):
    bpy.ops.import_scene.gltf(filepath=fp)
elif low.endswith('.stl'):
    bpy.ops.wm.stl_import(filepath=fp) if hasattr(bpy.ops.wm, 'stl_import') else bpy.ops.import_mesh.stl(filepath=fp)
elif low.endswith('.blend'):
    with bpy.data.libraries.load(fp) as (data_from, data_to):
        data_to.objects = data_from.objects
    for obj in data_to.objects:
        if obj is not None:
            bpy.context.collection.objects.link(obj)
else:
    raise RuntimeError("Unsupported import format: " + fp)
bpy.ops.wm.save_as_mainfile(filepath=r"{out}")
print("NEURON_BLENDER_OK import -> {out}")
'''


def script_export(path: str, fmt: str = "glb") -> str:
    p = Path(path).as_posix()
    fmt = (fmt or "glb").lower()
    return _header() + f'''
_ensure_object_mode()
fp = r"{p}"
fmt = "{fmt}"
bpy.ops.object.select_all(action='SELECT')
if fmt in ("glb", "gltf"):
    bpy.ops.export_scene.gltf(filepath=fp, export_format='GLB' if fmt=='glb' else 'GLTF_SEPARATE')
elif fmt == "fbx":
    bpy.ops.export_scene.fbx(filepath=fp)
elif fmt == "obj":
    bpy.ops.wm.obj_export(filepath=fp) if hasattr(bpy.ops.wm, 'obj_export') else bpy.ops.export_scene.obj(filepath=fp)
elif fmt == "stl":
    bpy.ops.wm.stl_export(filepath=fp) if hasattr(bpy.ops.wm, 'stl_export') else bpy.ops.export_mesh.stl(filepath=fp)
else:
    bpy.ops.wm.save_as_mainfile(filepath=fp)
print("NEURON_BLENDER_OK export_" + fmt + " -> " + fp)
'''


def script_texture(name: str = "NeuronTex") -> str:
    """Procedural texture via noise + color ramp on Principled BSDF."""
    return script_material(name=name, style="texture")


def list_assets() -> dict[str, Any]:
    root = assets_root()
    files = []
    for sub in ("exports", "renders", "scripts", "assets", "imports"):
        d = root / sub
        if not d.is_dir():
            continue
        for f in sorted(d.iterdir()):
            if f.is_file():
                files.append({"folder": sub, "name": f.name, "path": str(f), "bytes": f.stat().st_size})
    return {"root": str(root), "files": files[-80:], "count": len(files)}
