"""Phase 0 tool catalog — inventory of NEURON actions."""

LEGACY_EXECUTORS = [
    "open_app", "close_app", "steam_goto", "steam_select_account",
    "discord_friends", "open_settings", "replay_clicks",
    "learn_app", "train_pc", "training_status", "stop_training",
    "open_website", "search_site", "search_web",
    "type_text", "press_keys", "click", "move_mouse", "scroll", "page_scroll",
    "volume", "media", "window", "screenshot", "describe_screen",
    "play_result", "youtube_home", "youtube_home_play", "play_by_title",
    "list_visible_videos", "skip_ad", "fullscreen", "miniplayer",
    "player_key", "ensure_playback", "click_text", "computer_use",
    "create_folder", "create_file", "open_folder",
    "run_shell", "wait", "system_report",
]

NEW_TOOLS = [
    "get_running_apps", "get_windows", "get_active_window",
    "focus_app", "minimize_app", "maximize_app",
    "move_window", "move_window_to_monitor", "resize_window", "get_monitors",
    "get_windows_by_monitor",
    "press_key", "hotkey",
    "open_file", "search_files",
    "get_ui_tree", "get_active_window_elements",
    "find_ui_element", "click_ui_element",
    "get_element_text", "get_element_bounds",
    "browser_open", "browser_navigate", "browser_search",
    "browser_get_page", "browser_get_elements", "browser_find_element",
    "browser_click", "browser_type", "browser_scroll",
    "browser_back", "browser_forward",
    "browser_get_tabs", "browser_switch_tab", "browser_close_tab",
    "browser_research",
    "capture_screen", "capture_monitor",
    "get_cursor_position", "get_active_window_screenshot",
    "ocr_image", "detect_text_regions", "ocr_screen",
    "analyze_screen", "get_screen_context",
    "browser_read_page",
    "run_powershell", "web_search_summarize",
]

DEFAULT_RISK = {
    "open_app": "low", "close_app": "medium", "steam_goto": "medium",
    "steam_select_account": "medium", "discord_friends": "medium",
    "open_settings": "medium", "replay_clicks": "medium",
    "learn_app": "low", "train_pc": "low", "training_status": "low",
    "stop_training": "low", "open_website": "low", "search_site": "low",
    "search_web": "low", "type_text": "medium", "press_keys": "medium",
    "press_key": "medium", "hotkey": "medium",
    "click": "medium", "move_mouse": "low", "scroll": "low",
    "page_scroll": "low", "volume": "low", "media": "low", "window": "medium",
    "screenshot": "low", "describe_screen": "low", "play_result": "low",
    "youtube_home": "low", "youtube_home_play": "low", "play_by_title": "low",
    "list_visible_videos": "low", "skip_ad": "low", "fullscreen": "low",
    "miniplayer": "low", "player_key": "low", "ensure_playback": "low",
    "click_text": "medium", "computer_use": "medium",
    "create_folder": "medium", "create_file": "medium", "open_folder": "low",
    "open_file": "low", "search_files": "low",
    "run_shell": "high", "wait": "low", "system_report": "low",
    "get_running_apps": "low", "get_windows": "low", "get_active_window": "low",
    "focus_app": "low", "minimize_app": "low", "maximize_app": "low",
    "move_window": "medium", "move_window_to_monitor": "medium",
    "resize_window": "medium", "get_monitors": "low",
    "get_windows_by_monitor": "low",
    "get_ui_tree": "low", "get_active_window_elements": "low",
    "find_ui_element": "low", "click_ui_element": "medium",
    "get_element_text": "low", "get_element_bounds": "low",
    "browser_open": "low", "browser_navigate": "low", "browser_search": "low",
    "browser_get_page": "low", "browser_read_page": "low",
    "browser_get_elements": "low", "browser_find_element": "low",
    "browser_click": "medium", "browser_type": "medium", "browser_scroll": "low",
    "browser_back": "low", "browser_forward": "low",
    "browser_get_tabs": "low", "browser_switch_tab": "low", "browser_close_tab": "low",
    "browser_research": "low",
    "capture_screen": "low", "capture_monitor": "low",
    "get_cursor_position": "low", "get_active_window_screenshot": "low",
    "ocr_image": "low", "detect_text_regions": "low", "ocr_screen": "low",
    "analyze_screen": "low", "get_screen_context": "low",
    "run_powershell": "high", "web_search_summarize": "low",
}
