"""Phase 0 tool catalog — inventory of NEURON actions."""

LEGACY_EXECUTORS = [
    "open_app", "close_app", "steam_goto", "steam_select_account",
    "discord_friends", "open_settings", "replay_clicks",
    "learn_app", "train_pc", "training_status", "stop_training",
    "open_website", "search_site", "search_web",
    "type_text", "press_keys", "click", "move_mouse", "scroll", "page_scroll",
    "volume", "media", "window", "screenshot", "describe_screen",
    "play_result", "youtube_home", "youtube_home_play", "play_by_title",
    "list_visible_videos", "skip_ad", "fullscreen", "miniplayer",
    "player_key", "ensure_playback", "click_text", "computer_use",
    "create_folder", "create_file", "open_folder",
    "run_shell", "wait", "system_report",
]

NEW_TOOLS = [
    "get_running_apps", "get_windows", "get_active_window",
    "focus_app", "minimize_app", "maximize_app",
    "move_window", "move_window_to_monitor", "resize_window", "get_monitors",
    "get_windows_by_monitor",
    "press_key", "hotkey",
    "open_file", "search_files",
    "get_ui_tree", "get_active_window_elements",
    "find_ui_element", "click_ui_element", "click_element", "find_element",
    "get_element_text", "get_element_bounds",
    "browser_open", "browser_navigate", "browser_search",
    "browser_get_page", "browser_get_elements", "browser_find_element",
    "browser_click", "browser_type", "browser_scroll",
    "browser_back", "browser_forward",
    "browser_get_tabs", "browser_switch_tab", "browser_close_tab",
    "browser_research",
    "capture_screen", "capture_monitor",
    "get_cursor_position", "get_active_window_screenshot",
    "ocr_image", "detect_text_regions", "ocr_screen",
    "analyze_screen", "get_screen_context",
    "browser_read_page",
    "run_powershell", "web_search_summarize",
    # Domain skills (also registered as dotted names)
    "youtube_search", "youtube_play_result", "youtube_home", "youtube_play_search",
    "browser_open_tab", "windows_focus_app", "windows_move_to_monitor",
    "spotify_play", "discord_open_channel", "files_find", "files_open",
    "blender_open_project",
    # Phase 9 procedures
    "run_procedure", "blender_new_project",
]

DEFAULT_RISK = {
    # safe
    "open_app": "safe", "open_website": "safe", "search_site": "safe", "search_web": "safe",
    "focus_app": "safe", "minimize_app": "safe", "maximize_app": "safe",
    "move_window": "safe", "move_window_to_monitor": "safe", "resize_window": "safe",
    "get_running_apps": "safe", "get_windows": "safe", "get_active_window": "safe",
    "get_monitors": "safe", "get_windows_by_monitor": "safe",
    "scroll": "safe", "page_scroll": "safe", "move_mouse": "safe",
    "volume": "safe", "media": "safe",
    "screenshot": "safe", "describe_screen": "safe",
    "play_result": "safe", "youtube_home": "safe", "youtube_home_play": "safe",
    "play_by_title": "safe", "list_visible_videos": "safe", "skip_ad": "safe",
    "fullscreen": "safe", "miniplayer": "safe", "player_key": "safe", "ensure_playback": "safe",
    "open_folder": "safe", "open_file": "safe", "search_files": "safe",
    "learn_app": "safe", "train_pc": "safe", "training_status": "safe", "stop_training": "safe",
    "wait": "safe", "system_report": "safe", "web_search_summarize": "safe",
    "browser_open": "safe", "browser_navigate": "safe", "browser_search": "safe",
    "browser_get_page": "safe", "browser_read_page": "safe",
    "browser_get_elements": "safe", "browser_find_element": "safe",
    "browser_scroll": "safe", "browser_back": "safe", "browser_forward": "safe",
    "browser_get_tabs": "safe", "browser_switch_tab": "safe", "browser_research": "safe",
    "capture_screen": "safe", "capture_monitor": "safe",
    "get_cursor_position": "safe", "get_active_window_screenshot": "safe",
    "ocr_image": "safe", "detect_text_regions": "safe", "ocr_screen": "safe",
    "analyze_screen": "safe", "get_screen_context": "safe",
    "get_ui_tree": "safe", "get_active_window_elements": "safe",
    "find_ui_element": "safe", "find_element": "safe",
    "get_element_text": "safe", "get_element_bounds": "safe",
    # confirm
    "type_text": "confirm", "computer_use": "confirm",
    "browser_type": "confirm",
    "create_folder": "confirm", "create_file": "confirm",
    "close_app": "confirm",
    "replay_clicks": "confirm", "steam_select_account": "confirm",
    # interactive — content heuristics may elevate to confirm/high/blocked
    "press_keys": "safe", "press_key": "safe", "hotkey": "safe",
    "click": "safe", "click_text": "safe", "click_ui_element": "safe",
    "click_element": "safe", "browser_click": "safe", "browser_close_tab": "safe",
    "window": "safe", "steam_goto": "safe", "discord_friends": "safe",
    "open_settings": "safe",
    # high / blocked via content heuristics in safety.levels
    "run_shell": "high", "run_powershell": "high",
    # Domain skills (safe defaults; content can elevate)
    "youtube_search": "safe", "youtube_play_result": "safe", "youtube_home": "safe",
    "youtube_play_search": "safe", "youtube_fullscreen": "safe", "youtube_skip_ad": "safe",
    "browser_open_tab": "safe", "windows_focus_app": "safe", "windows_move_to_monitor": "safe",
    "spotify_play": "safe", "spotify_pause": "safe", "discord_open_channel": "safe",
    "files_find": "safe", "files_open": "safe", "blender_open_project": "safe",
    "run_procedure": "safe", "blender_new_project": "safe",
}
